
const Type = {
  GET_ALL_NEWS: 'GET_ALL_NEWS',
  GET_WEATHER: 'GET_WEATHER',
  MAIN_THEME: 'MAIN_THEME',
  SECONDARY_THEME: 'SECONDARY_THEME',
  CHANGE_LANG: 'CHANGE_LANG',
  MAIN_PAGE: 'MAIN_PAGE',
  NEWS_PAGE: 'NEWS_PAGE',
  SHOW_WARNING: 'SHOW_WARNING',
  REMOVE_WARNING: 'REMOVE_WARNING',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  ADD_KEY: 'ADD_KEY',
  DELETE_KEY: 'DELETE_KEY',
  UPDATE_KEYS: 'UPDATE_KEYS',
  SEARCH_RESULT: 'SEARCH_RESULT',
  UPDATE_CHOISE: 'UPDATE_CHOISE',
}
export default Type
