
const Type = {
  GET_ALL_NEWS: 'GET_ALL_NEWS',
  MAIN_THEME: 'MAIN_THEME',
  SECONDARY_THEME: 'SECONDARY_THEME',
  CHANGE_LANG: 'CHANGE_LANG',
  MAIN_PAGE: 'MAIN_PAGE',
  NEWS_PAGE: 'NEWS_PAGE',
  SHOW_WARNING: 'SHOW_WARNING',
  REMOVE_WARNING: 'REMOVE_WARNING',

}
export default Type
